//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAIHOI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAIHOI.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng cổ phiếu bầu đã lớn hơn số lượng cổ phiếu hiện có.
        /// </summary>
        public static string alertbaucu {
            get {
                return ResourceManager.GetString("alertbaucu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả bầu Hội Đồng Quản Trị đã được lưu thành công.
        /// </summary>
        public static string alertbaucu1 {
            get {
                return ResourceManager.GetString("alertbaucu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thay đổi ..
        /// </summary>
        public static string alertbaucuhtml {
            get {
                return ResourceManager.GetString("alertbaucuhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tiếp tục để chuyển sang trang In kết quả.
        /// </summary>
        public static string alertbaucuhtml1 {
            get {
                return ResourceManager.GetString("alertbaucuhtml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa đưa ra ý kiến cho nội dung biểu quyết số.
        /// </summary>
        public static string alertbieuquyet1 {
            get {
                return ResourceManager.GetString("alertbieuquyet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả biểu quyết đã được lưu thành công.
        /// </summary>
        public static string alertbieuquyet2 {
            get {
                return ResourceManager.GetString("alertbieuquyet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn nộp phiếu này ?.
        /// </summary>
        public static string alertbieuquyet3 {
            get {
                return ResourceManager.GetString("alertbieuquyet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn chọn biểu quyết này ?.
        /// </summary>
        public static string alertbieuquyet4 {
            get {
                return ResourceManager.GetString("alertbieuquyet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tiếp tục để bầu hội đồng quản trị.
        /// </summary>
        public static string alertbieuquyethtml2 {
            get {
                return ResourceManager.GetString("alertbieuquyethtml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các kết quả đã lưu sẽ không thể thay đổi !.
        /// </summary>
        public static string alertbieuquyethtml3 {
            get {
                return ResourceManager.GetString("alertbieuquyethtml3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các biểu quyết đã chọn sẽ không thể thay đổi .
        /// </summary>
        public static string alertbieuquyethtml4 {
            get {
                return ResourceManager.GetString("alertbieuquyethtml4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra, mật khẩu mới đã được gửi tới email.
        /// </summary>
        public static string alertcheckemail {
            get {
                return ResourceManager.GetString("alertcheckemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại kết nối Internet.
        /// </summary>
        public static string alertcheckinternet {
            get {
                return ResourceManager.GetString("alertcheckinternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập email.
        /// </summary>
        public static string alertchuanhapmacd {
            get {
                return ResourceManager.GetString("alertchuanhapmacd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tài khoản và mật khẩu của bạn!.
        /// </summary>
        public static string alertdiendaydu {
            get {
                return ResourceManager.GetString("alertdiendaydu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đổi mật khẩu của bạn trong lần đăng nhập đầu tiên.
        /// </summary>
        public static string alertdoimatkhau {
            get {
                return ResourceManager.GetString("alertdoimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu chưa đủ mạnh để đáp ứng yêu cầu của hệ thống.
        /// </summary>
        public static string alertdoimatkhau1 {
            get {
                return ResourceManager.GetString("alertdoimatkhau1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng liên hệ để được hỗ trợ.
        /// </summary>
        public static string alerthotro {
            get {
                return ResourceManager.GetString("alerthotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string alerthotrothanhcong {
            get {
                return ResourceManager.GetString("alerthotrothanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã phản hồi.
        /// </summary>
        public static string alerthotrothanhconghtml {
            get {
                return ResourceManager.GetString("alerthotrothanhconghtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tiếp tục để tải về kết quả.
        /// </summary>
        public static string alertketquahtml {
            get {
                return ResourceManager.GetString("alertketquahtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi, mật khẩu của bạn không chính xác. Vui lòng kiểm tra lại mật khẩu của bạn..
        /// </summary>
        public static string alertkhongchinhxac {
            get {
                return ResourceManager.GetString("alertkhongchinhxac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email bạn nhập không tồn tại, vui lòng thử lại.
        /// </summary>
        public static string alertmacd {
            get {
                return ResourceManager.GetString("alertmacd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tiếp tục để xác nhận thông tin.
        /// </summary>
        public static string alertmatkhauhtml {
            get {
                return ResourceManager.GetString("alertmatkhauhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công! Mật khẩu đã được thay đổi!.
        /// </summary>
        public static string alertmatkhauthanhcong {
            get {
                return ResourceManager.GetString("alertmatkhauthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email  và hệ thống sẽ gửi mật khẩu mới tới Email mà bạn đã đăng ký.
        /// </summary>
        public static string alertquenmatkhau {
            get {
                return ResourceManager.GetString("alertquenmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn tải lại trang ?.
        /// </summary>
        public static string alerttailaitrang {
            get {
                return ResourceManager.GetString("alerttailaitrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các phiếu bầu sẽ được làm mới !.
        /// </summary>
        public static string alerttailaitranghtml {
            get {
                return ResourceManager.GetString("alerttailaitranghtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn xác nhận thông tin ?.
        /// </summary>
        public static string alertthongtin1 {
            get {
                return ResourceManager.GetString("alertthongtin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đã xác nhận sẽ không thể thay đổi.
        /// </summary>
        public static string alertthongtinhtml1 {
            get {
                return ResourceManager.GetString("alertthongtinhtml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thử lại.
        /// </summary>
        public static string alertthulai {
            get {
                return ResourceManager.GetString("alertthulai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tiêu đề.
        /// </summary>
        public static string alerttieude {
            get {
                return ResourceManager.GetString("alerttieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thông tin thành công.
        /// </summary>
        public static string alertxacnhan {
            get {
                return ResourceManager.GetString("alertxacnhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu biểu quyết.
        /// </summary>
        public static string alertxacnhanbtn {
            get {
                return ResourceManager.GetString("alertxacnhanbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn &lt;strong&gt;Bắt đầu biểu quyết&lt;/strong&gt; để tiếp tục..
        /// </summary>
        public static string alertxacnhanhtml {
            get {
                return ResourceManager.GetString("alertxacnhanhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU BẦU HỘI ĐỒNG QUẢN TRỊ.
        /// </summary>
        public static string bauhdqt {
            get {
                return ResourceManager.GetString("bauhdqt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU BIỂU QUYẾT.
        /// </summary>
        public static string bieuquyet {
            get {
                return ResourceManager.GetString("bieuquyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi mật khẩu mới đến email.
        /// </summary>
        public static string btnguimatkhau {
            get {
                return ResourceManager.GetString("btnguimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu mới ....
        /// </summary>
        public static string entermatkhaumoi {
            get {
                return ResourceManager.GetString("entermatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾT QUẢ BẦU HỘI ĐỒNG QUẢN TRỊ.
        /// </summary>
        public static string kqbauhdqt {
            get {
                return ResourceManager.GetString("kqbauhdqt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾT QUẢ BIỂU QUYẾT.
        /// </summary>
        public static string kqbieuquyet {
            get {
                return ResourceManager.GetString("kqbieuquyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bầu Hội Đồng Quản Trị.
        /// </summary>
        public static string lbbauhdqt {
            get {
                return ResourceManager.GetString("lbbauhdqt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu quyết chương trình đại hội.
        /// </summary>
        public static string lbbieuquyetdaihoi {
            get {
                return ResourceManager.GetString("lbbieuquyetdaihoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu quyết biên bản, nghị quyết.
        /// </summary>
        public static string lbbieuquyetnghiquyet {
            get {
                return ResourceManager.GetString("lbbieuquyetnghiquyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu quyết các tờ trình.
        /// </summary>
        public static string lbbieuquyettotrinh {
            get {
                return ResourceManager.GetString("lbbieuquyettotrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chắc chắn.
        /// </summary>
        public static string lbchacchan {
            get {
                return ResourceManager.GetString("lbchacchan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng đến với đại hội đồng cổ đông bất thường năm 2020 của .
        /// </summary>
        public static string lbchaomung {
            get {
                return ResourceManager.GetString("lbchaomung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string lbchucvu {
            get {
                return ResourceManager.GetString("lbchucvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        public static string lbcmnd {
            get {
                return ResourceManager.GetString("lbcmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổ phiếu.
        /// </summary>
        public static string lbcophieu {
            get {
                return ResourceManager.GetString("lbcophieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phiếu còn lại.
        /// </summary>
        public static string lbcophieuconlai {
            get {
                return ResourceManager.GetString("lbcophieuconlai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phiếu đã bầu.
        /// </summary>
        public static string lbcophieudabau {
            get {
                return ResourceManager.GetString("lbcophieudabau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện.
        /// </summary>
        public static string lbdaidien {
            get {
                return ResourceManager.GetString("lbdaidien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string lbdangnhap {
            get {
                return ResourceManager.GetString("lbdangnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string lbdangxuat {
            get {
                return ResourceManager.GetString("lbdangxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string lbdienthoai {
            get {
                return ResourceManager.GetString("lbdienthoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string lbdoimatkhau {
            get {
                return ResourceManager.GetString("lbdoimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải xuống.
        /// </summary>
        public static string lbdownload {
            get {
                return ResourceManager.GetString("lbdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIÂY.
        /// </summary>
        public static string lbgiay {
            get {
                return ResourceManager.GetString("lbgiay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỜ.
        /// </summary>
        public static string lbgio {
            get {
                return ResourceManager.GetString("lbgio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        public static string lbhethong {
            get {
                return ResourceManager.GetString("lbhethong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỆ THỐNG BỎ PHIẾU TRỰC TUYẾN.
        /// </summary>
        public static string lbhethongbophieu {
            get {
                return ResourceManager.GetString("lbhethongbophieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        public static string lbhoantat {
            get {
                return ResourceManager.GetString("lbhoantat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Vui lòng quay lại sau.
        /// </summary>
        public static string lbhoatdong {
            get {
                return ResourceManager.GetString("lbhoatdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại hội đồng cổ đông thường niên sẽ bắt đầu vào lúc 9:30 sáng 28-04-2020.
        /// </summary>
        public static string lbhoatdong0 {
            get {
                return ResourceManager.GetString("lbhoatdong0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string lbhoten {
            get {
                return ResourceManager.GetString("lbhoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string lbhuy {
            get {
                return ResourceManager.GetString("lbhuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In phiếu biểu quyết.
        /// </summary>
        public static string lbinketqua {
            get {
                return ResourceManager.GetString("lbinketqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin không chính xác.
        /// </summary>
        public static string lbkhongchinhxac {
            get {
                return ResourceManager.GetString("lbkhongchinhxac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thành công.
        /// </summary>
        public static string lbkhongthanhcong {
            get {
                return ResourceManager.GetString("lbkhongthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string lblienhehotro {
            get {
                return ResourceManager.GetString("lblienhehotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string lbmatkhau {
            get {
                return ResourceManager.GetString("lbmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string lbmatkhaumoi {
            get {
                return ResourceManager.GetString("lbmatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGÀY.
        /// </summary>
        public static string lbngay {
            get {
                return ResourceManager.GetString("lbngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày cấp.
        /// </summary>
        public static string lbngaycap {
            get {
                return ResourceManager.GetString("lbngaycap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email của bạn ....
        /// </summary>
        public static string lbnhapmacodong {
            get {
                return ResourceManager.GetString("lbnhapmacodong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nơi cấp.
        /// </summary>
        public static string lbnoicap {
            get {
                return ResourceManager.GetString("lbnoicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string lbnoidung {
            get {
                return ResourceManager.GetString("lbnoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHẢN HỒI.
        /// </summary>
        public static string lbphanhoi {
            get {
                return ResourceManager.GetString("lbphanhoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu bầu.
        /// </summary>
        public static string lbphieubieuquyet {
            get {
                return ResourceManager.GetString("lbphieubieuquyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÚT.
        /// </summary>
        public static string lbphut {
            get {
                return ResourceManager.GetString("lbphut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu ?.
        /// </summary>
        public static string lbquenmatkhau {
            get {
                return ResourceManager.GetString("lbquenmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp diễn ra.
        /// </summary>
        public static string lbsapdienra {
            get {
                return ResourceManager.GetString("lbsapdienra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng cổ phiếu.
        /// </summary>
        public static string lbslcophieu {
            get {
                return ResourceManager.GetString("lbslcophieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phiếu bầu.
        /// </summary>
        public static string lbslphieubau {
            get {
                return ResourceManager.GetString("lbslphieubau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số phiếu bầu.
        /// </summary>
        public static string lbslphieubieuquyet {
            get {
                return ResourceManager.GetString("lbslphieubieuquyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND số.
        /// </summary>
        public static string lbsocmnd {
            get {
                return ResourceManager.GetString("lbsocmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string lbtaikhoan {
            get {
                return ResourceManager.GetString("lbtaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại .
        /// </summary>
        public static string lbtailai {
            get {
                return ResourceManager.GetString("lbtailai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        public static string lbtailieu {
            get {
                return ResourceManager.GetString("lbtailieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cổ đông.
        /// </summary>
        public static string lbtencodong {
            get {
                return ResourceManager.GetString("lbtencodong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string lbthongbao {
            get {
                return ResourceManager.GetString("lbthongbao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string lbthongtin {
            get {
                return ResourceManager.GetString("lbthongtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cổ đông.
        /// </summary>
        public static string lbthongtincodong {
            get {
                return ResourceManager.GetString("lbthongtincodong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        public static string lbtieptuc {
            get {
                return ResourceManager.GetString("lbtieptuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string lbtieude {
            get {
                return ResourceManager.GetString("lbtieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ sở hữu (%).
        /// </summary>
        public static string lbtilesohuu {
            get {
                return ResourceManager.GetString("lbtilesohuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vấn đề để được hỗ trợ.
        /// </summary>
        public static string lbvande {
            get {
                return ResourceManager.GetString("lbvande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thông tin.
        /// </summary>
        public static string lbxacnhanthongtin {
            get {
                return ResourceManager.GetString("lbxacnhanthongtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LƯU Ý : Tổng số lượng cổ phiếu bầu phải nhỏ hơn hoặc bằng số lượng cổ phiếu đang sở hữu..
        /// </summary>
        public static string luuy {
            get {
                return ResourceManager.GetString("luuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rấc tiếc, nhập lại không chính xác.
        /// </summary>
        public static string placehodernhaplai {
            get {
                return ResourceManager.GetString("placehodernhaplai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới ....
        /// </summary>
        public static string reentermatkhaumoi {
            get {
                return ResourceManager.GetString("reentermatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu.
        /// </summary>
        public static string yeucau {
            get {
                return ResourceManager.GetString("yeucau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ít nhất 6 ký tự.
        /// </summary>
        public static string yeucau6kytu {
            get {
                return ResourceManager.GetString("yeucau6kytu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ít nhất 1 chữ in hoa (A-Z).
        /// </summary>
        public static string yeucauinhoa {
            get {
                return ResourceManager.GetString("yeucauinhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ít nhất 1 số (0-9).
        /// </summary>
        public static string yeucauso {
            get {
                return ResourceManager.GetString("yeucauso", resourceCulture);
            }
        }
    }
}
