//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAIHOI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401084734-c-tt78admin.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_pypharm_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_pypharm_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401084734-c-tt78admin.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_pypharm_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_pypharm_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401084734-c-tt78admin.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_pypharm_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_pypharm_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401084734-c-tt78admin.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_pypharm_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_pypharm_publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharmhcm-tt78admin.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_pypharmhcm_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_pypharmhcm_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharmhcm-tt78admin.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_pypharmhcm_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_pypharmhcm_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharmhcm-tt78admin.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_pypharmhcm_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_pypharmhcm_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharmhcm-tt78admin.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_pypharmhcm_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_pypharmhcm_publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharrm-tt78admindemo.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_pypharmtest_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_pypharmtest_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharrm-tt78admindemo.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_pypharmtest_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_pypharmtest_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharrm-tt78admindemo.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_pypharmtest_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_pypharmtest_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pypharrm-tt78admindemo.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_pypharmtest_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_pypharmtest_publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://3200042637-tt78admin.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_quangtri_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_quangtri_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://3200042637-tt78admin.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_quangtri_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_quangtri_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://3200042637-tt78admin.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_quangtri_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_quangtri_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://3200042637-tt78admin.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_quangtri_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_quangtri_publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401062392-tt78admin.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_asta_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_asta_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401062392-tt78admin.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_asta_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_asta_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401062392-tt78admin.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_asta_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_asta_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401062392-tt78admin.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_asta_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_asta_publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bqlc-tt78admindemo.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_astatest_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_astatest_publish_PublishService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bqlc-tt78admindemo.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_astatest_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_astatest_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bqlc-tt78admindemo.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_astatest_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_astatest_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bqlc-tt78admindemo.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_astatest_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_astatest_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401111868-tt78cadmin.vnpt-invoice.com.vn/businessService.asmx")]
        public string DAIHOI_nghinhphong_business_BusinessService {
            get {
                return ((string)(this["DAIHOI_nghinhphong_business_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401111868-tt78cadmin.vnpt-invoice.com.vn/ExtMienTrungService.asmx")]
        public string DAIHOI_nghinhphong_extmientrung_ExtMienTrungService {
            get {
                return ((string)(this["DAIHOI_nghinhphong_extmientrung_ExtMienTrungService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401111868-tt78cadmin.vnpt-invoice.com.vn/portalService.asmx")]
        public string DAIHOI_nghinhphong_portal_PortalService {
            get {
                return ((string)(this["DAIHOI_nghinhphong_portal_PortalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4401111868-tt78cadmin.vnpt-invoice.com.vn/publishService.asmx")]
        public string DAIHOI_nghinhphong_publish_PublishService {
            get {
                return ((string)(this["DAIHOI_nghinhphong_publish_PublishService"]));
            }
        }
    }
}
