//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAIHOI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_LICHSUPHATHANH
    {
        public int Id { get; set; }
        public string macn { get; set; }
        public string fkey { get; set; }
        public string result { get; set; }
        public string sohddt { get; set; }
    }
}
