//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAIHOI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCTAIKHOAN
    {
        public string macn { get; set; }
        public string accservice { get; set; }
        public string passservice { get; set; }
        public string accadmin { get; set; }
        public string passadmin { get; set; }
        public string tencn { get; set; }
        public string diachi { get; set; }
        public string mst { get; set; }
        public string taikhoannh { get; set; }
        public string tennh { get; set; }
        public string dienthoai { get; set; }
    }
}
